name: Periodic Health Check

on: 
  schedule:
    - cron: '0 * * * * ' #on the hour every hour
  
jobs:
  periodic healthcheck:
    runs-on: ubuntu-20.04
    steps:
      - uses: jtalk/url-health-check-action@v3
        with:
          url: https://fullstackopen-pokedex.onrender.com/health
     