name: Periodic Health Check

on: 
  schedule:
    - cron: '*/5 * * * *' #every 5min
  push:
    branches:
      - master
  
jobs:
  periodic-healthcheck:
    runs-on: ubuntu-20.04
    steps:
      - uses: fjogeleit/http-request-action@v1
        with:
          url: 'http://localhost:5000/health'
          method: 'GET'
      #- uses: jtalk/url-health-check-action@v3
        #with:
          #url: https://fullstackopen-pokedex.onrender.com/health
     