name: Periodic Health Check

on: 
  schedule:
    -cron: '*/5 * * * *' #every 5min
  
jobs:
  
  periodic healthcheck:
  steps:
  - name: Check the deployed service URL
    uses: jtalk/url-health-check-action@v3
    with:
      # Check the following URLs one by one sequentially
      url: https://fullstackopen-pokedex.onrender.com/health
     