name: Periodic Health Check

on: 
  schedule:
    - cron: '0 0 * * *' #once a day
  
jobs:
  periodic_healthcheck:
    runs-on: ubuntu-20.04
    steps:
      - uses: jtalk/url-health-check-action@v3
        with:
          url: https://fullstackopen-pokedex.onrender.com/health
     
